version: "3.9" # optional since v1.27.0
services:
  api:
    build:
      context: api
    image: ghcr.io/gitvision-io/git-dashboard_api:latest
    ports:
      - "3001:3001"
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - redis

  client:
    build:
      context: client
    image: ghcr.io/gitvision-io/git-dashboard_client:latest
    environment:
      SERVER_API_URL: http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      - api

  redis:
    image: redis
    ports:
      - "6379:6379"
