name: git-pull-cloud

on:
  push:
    branches:
      - "main-public"

jobs:
  merge-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_KEY }}

      - name: Merge main-public to staging
        run: |
          git fetch
          git checkout staging
          git merge origin/main-public
          git push origin staging
